name: CI

on:
  push:
    branches: [ task6 ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Preparing and include GoogleTests
        run: |
          cd task6/task-ci/B
          git submodule add https://github.com/google/googletest ../3rdparty
          cmake .. && make
      - name: F 
        uses: akhtyamovpavel/ActionGtestReport@v0.0.9
        with:
          exec-path: bin/CTestExe
          report-path: report.xml
          working-directory: task6/task-ci
        
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Distributive
          path: |
            task6/task-ci/bin
            task6/task-ci/lib
